services:
    database:
        image: mariadb:latest
        container_name: database
        volumes:
            - ./storage/database:/var/lib/mysql
        environment:
            - MARIADB_DATABASE=minecraft
            - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=1
    proxy:
        image: amazoncorretto:17
        container_name: proxy
        depends_on:
            - database
        ports:
            - "25565:25565"
        volumes:
            - ./storage/proxy:/server
            - ./proxy/waterfall.jar:/server/server.jar
            - ./proxy/config.yml:/server/config.yml
            - ./proxy/plugins/TerraPlusMinusBungeeBridge-1.0-SNAPSHOT.jar:/server/plugins/terraplusminusbungeebridge.jar
            - ./proxy/plugins/BungeeSafeguard-3.1-SNAPSHOT-all.jar:/server/plugins/bungeesafeguard.jar
            - ./proxy/plugins/LuckPerms-Bungee-5.4.117.jar:/server/plugins/luckperms.jar
            - ./proxy/plugins/BungeeSafeguard/config.yml:/server/plugins/BungeeSafeguard/config.yml
            - ./proxy/plugins/LuckPerms/config.yml:/server/plugins/LuckPerms/config.yml
        working_dir: /server
        entrypoint:
            - java
            - -jar
            - server.jar
    s0:
        image: amazoncorretto:17
        container_name: s0
        depends_on:
            - proxy
        volumes:
            - ./storage/0:/server
            - ./shared/default-startup.sh:/server/startup.sh
            - ./shared/paper-1.20.2.jar:/server/server.jar
            - ./shared/eula.txt:/server/eula.txt
            - ./shared/bukkit.yml:/server/bukkit.yml
            - ./shared/spigot.yml:/server/spigot.yml
            - ./shared/server.properties:/server/server.properties
            - ./shared/config/paper-global-main.yml:/server/config/paper-global-main.yml
            - ./shared/plugins/EssentialsX-2.21.0-dev+25-fbfd7e9.jar:/server/plugins/essentialsx.jar
            - ./shared/plugins/LuckPerms-Bukkit-5.4.108.jar:/server/plugins/luckperms.jar
            - ./shared/plugins/terraplusminus-1.3.2.jar:/server/plugins/terraplusminus.jar
            - ./shared/plugins/worldedit-bukkit-7.2.17.jar:/server/plugins/worldedit.jar
            - ./shared/plugins/LuckPerms/config.yml:/server/plugins/LuckPerms/config.yml
            - ./shared/plugins/Essentials/motd.txt:/server/plugins/Essentials/motd.txt
            - ./shared/plugins/Essentials/config.yml:/server/plugins/Essentials/config.yml
            - ./shared/plugins/WorldEdit/config.yml:/server/plugins/WorldEdit/config.yml
            - ./0/plugins/Terraplusminus/config.yml:/server/plugins/Terraplusminus/config.yml
        working_dir: /server
        entrypoint:
            - sh
            - startup.sh
    s1500:
        image: amazoncorretto:17
        container_name: s1500
        depends_on:
            - proxy
        volumes:
            - ./storage/1500:/server
            - ./shared/default-startup.sh:/server/startup.sh
            - ./shared/paper-1.20.2.jar:/server/server.jar
            - ./shared/eula.txt:/server/eula.txt
            - ./shared/bukkit.yml:/server/bukkit.yml
            - ./shared/spigot.yml:/server/spigot.yml
            - ./shared/server.properties:/server/server.properties
            - ./shared/config/paper-global-main.yml:/server/config/paper-global-main.yml
            - ./shared/plugins/EssentialsX-2.21.0-dev+25-fbfd7e9.jar:/server/plugins/essentialsx.jar
            - ./shared/plugins/LuckPerms-Bukkit-5.4.108.jar:/server/plugins/luckperms.jar
            - ./shared/plugins/terraplusminus-1.3.2.jar:/server/plugins/terraplusminus.jar
            - ./shared/plugins/worldedit-bukkit-7.2.17.jar:/server/plugins/worldedit.jar
            - ./shared/plugins/LuckPerms/config.yml:/server/plugins/LuckPerms/config.yml
            - ./shared/plugins/Essentials/motd.txt:/server/plugins/Essentials/motd.txt
            - ./shared/plugins/Essentials/config.yml:/server/plugins/Essentials/config.yml
            - ./shared/plugins/WorldEdit/config.yml:/server/plugins/WorldEdit/config.yml
            - ./1500/plugins/Terraplusminus/config.yml:/server/plugins/Terraplusminus/config.yml
        working_dir: /server
        entrypoint:
            - sh
            - startup.sh
    s3000:
        image: amazoncorretto:17
        container_name: s3000
        depends_on:
            - proxy
        volumes:
            - ./storage/3000:/server
            - ./shared/default-startup.sh:/server/startup.sh
            - ./shared/paper-1.20.2.jar:/server/server.jar
            - ./shared/eula.txt:/server/eula.txt
            - ./shared/bukkit.yml:/server/bukkit.yml
            - ./shared/spigot.yml:/server/spigot.yml
            - ./shared/server.properties:/server/server.properties
            - ./shared/config/paper-global-main.yml:/server/config/paper-global-main.yml
            - ./shared/plugins/EssentialsX-2.21.0-dev+25-fbfd7e9.jar:/server/plugins/essentialsx.jar
            - ./shared/plugins/LuckPerms-Bukkit-5.4.108.jar:/server/plugins/luckperms.jar
            - ./shared/plugins/terraplusminus-1.3.2.jar:/server/plugins/terraplusminus.jar
            - ./shared/plugins/worldedit-bukkit-7.2.17.jar:/server/plugins/worldedit.jar
            - ./shared/plugins/LuckPerms/config.yml:/server/plugins/LuckPerms/config.yml
            - ./shared/plugins/Essentials/motd.txt:/server/plugins/Essentials/motd.txt
            - ./shared/plugins/Essentials/config.yml:/server/plugins/Essentials/config.yml
            - ./shared/plugins/WorldEdit/config.yml:/server/plugins/WorldEdit/config.yml
            - ./3000/plugins/Terraplusminus/config.yml:/server/plugins/Terraplusminus/config.yml
        working_dir: /server
        entrypoint:
            - sh
            - startup.sh